name: Project pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # ********** LINUX PIPESTEPS ***************** #
  # ********** BUILD *************************** #
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev

      - name: Build submodules
        run: git submodule update --init

      - name: Configure Wayland+X11 static library
        run: cmake -B build-full-static -D GLFW_BUILD_WAYLAND=ON -D GLFW_BUILD_X11=ON
      
      - name: Build Wayland+X11 static library
        run: cmake --build build-full-static --parallel
  # ********** TEST *************************** #
  run-tests-linux:
        runs-on: ubuntu-latest
        needs: [build-linux]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Build tests folder
              run: |
                cd test
                mkdir build
                cd build
            - name: Create executable
              run: |
                cmake ..
                make
            - name: Runing tests
              run: |
                ./lypo_engine_test

                if [ $? != 0 ]
                  echo "Some tests failed!"
                  exit 1
                else
                  echo "All tests passed!"
                fi
  # ********** ARTIFACT *************************** #
  save-artifact-linux:
        runs-on: ubuntu-latest
        needs: [run-tests-linux]
        steps:
          - uses: actions/upload-artifact@v4
            with:
              name: build-static-linux
              path: ./build-full-static/lypo_engine
  




  
  # ********** WINDOWS PIPESTEPS ***************** #
  # ********** BUILD *************************** #
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build submodules
        run: git submodule update --init

      - name: Configure Win32 static x64 library
        run: cmake -B build-win32-static-x64 -G "Visual Studio 17 2022" -A x64

      - name: Build Win32 static x64 library
        run: cmake --build build-win32-static-x64 --parallel
  # ********** TEST *************************** #
  run-tests-windows:
        runs-on: windows-latest
        needs: [build-windows]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Build tests folder
              run: |
                cd test
                mkdir build
                cd build
            - name: Create executable
              run: |
                cmake ..
                make
            - name: Runing tests
              run: |
                ./lypo_engine_test.exe
                
                if ($? -eq 0) {
                  "All test passed!"
                }
                else {
                  "Some tests failed!"
                  exit 1
                }
  # ********** ARTIFACT *************************** #
  save-artifact-windows:
        runs-on: windows-latest
        needs: [run-tests]
        steps:
            - uses: actions/upload-artifact@v4
              with:
                name: build-static-windows
                path: ./build-full-static/lypo_engine.exe