name: Build cpp project with CMake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            sudo apt update
            sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev

      - name: Build submodules
        run: git submodule update --init

      - name: Create build directory
        run: mkdir -p build

      - name: Configure Wayland+X11 static library
        run: cmake -B build-full-static -D GLFW_BUILD_WAYLAND=ON -D GLFW_BUILD_X11=ON
      
      - name: Build Wayland+X11 static library
        run: cmake --build build-full-static --parallel

        # Ajouter apres les runs de tests

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build submodules
        run: git submodule update --init

      - name: Set up CMake
        uses: kitware/cmake@v3
        with:
          cmake-version: '3.26.0' # Spécifie la version de CMake

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        run: .\build\my_program.exe
