name: Build cpp project with CMake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build submodules
        run: git submodule update --init

      - name: Set up CMake
        uses: cmake/ctest-nightly@v2
        with: 
          cmake-version: '3.26.0'

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build

        # Ajouter apres les runs de tests

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build submodules
        run: git submodule update --init

      - name: Set up CMake
        uses: kitware/cmake@v3
        with:
          cmake-version: '3.26.0' # Spécifie la version de CMake

      - name: Create build directory
        run: mkdir build

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        run: .\build\my_program.exe
