name: Build cpp project with CMake

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
