name: Windows Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    install-project:
        runs-on: windows-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Build submodules
              run: git submodule update --init

            - name: Configure Win32 static x64 library
              run: cmake -B build-win32-static-x64 -G "Visual Studio 17 2022" -A x64

            - name: Build Win32 static x64 library
              run: cmake --build build-win32-static-x64 --parallel
    
    run-tests:
        runs-on: windows-latest
        needs: [install-project]
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Build tests folder
              run: |
                cd test
                mkdir build
                cd build
            - name: Create executable
              run: |
                cmake ..
                make
            - name: Runing tests
              run: |
                ./lypo_engine_test.exe
                
                if ($? -eq 0) {
                  "All test passed!"
                }
                else {
                  "Some tests failed!"
                  exit 1
                }

    save-artifact:
        runs-on: windows-latest
        needs: [run-tests]
        steps:
            - uses: actions/upload-artifact@v4
              with:
                name: build-static-windows
                path: ./build-full-static/lypo_engine.exe
